//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdded_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAdded_service()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
        }
    
        public int ID { get; set; }
        public int Client_id { get; set; }
        public int Service_id { get; set; }
        public int Quantity { get; set; }
        public int Payable_amount { get; set; }
        public System.DateTime Added_date { get; set; }
    
        public virtual tblClient_profile tblClient_profile { get; set; }
        public virtual tblCompany_services tblCompany_services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
    }
}
