//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient_transaction
    {
        public int ID { get; set; }
        public int Invoice_id { get; set; }
        public int Paid_amount { get; set; }
        public System.DateTime Paid_date { get; set; }
    
        public virtual tblInvoice tblInvoice { get; set; }
    }
}
