//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Client_ManagementEntities : DbContext
    {
        public Client_ManagementEntities()
            : base("name=Client_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdded_service> tblAdded_service { get; set; }
        public virtual DbSet<tblClient_profile> tblClient_profile { get; set; }
        public virtual DbSet<tblClient_transaction> tblClient_transaction { get; set; }
        public virtual DbSet<tblCompany_services> tblCompany_services { get; set; }
        public virtual DbSet<tblInvoice> tblInvoices { get; set; }
    }
}
