//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient_transaction
    {
        public int ID { get; set; }
        public int Client_id { get; set; }
        public int Invoice_id { get; set; }
        public Nullable<int> Paid_amount { get; set; }
        public Nullable<System.DateTime> Paid_date { get; set; }
        public Nullable<int> Payment_type { get; set; }
    
        public virtual tblClient_profile tblClient_profile { get; set; }
        public virtual tblAdded_service tblAdded_service { get; set; }
        public virtual tblCompany_services tblCompany_Services { get; set; }
    }
}
