//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoice
    {
        public int ID { get; set; }
        public Nullable<int> Invoice_no { get; set; }
        public Nullable<int> Added_service_id { get; set; }
        public Nullable<int> Payment_status { get; set; }
        public Nullable<int> Payment_type { get; set; }
        public Nullable<int> Due { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tblAdded_service tblAdded_service { get; set; }
    }
}
